### ISSUE TITLE
Add in-class exercise to class on Agile

### ISSUE THREAD

**Issue by EvanDorsky** [olinjs/olinjs#103]
This might be fun to break up the lecture. Something comparing the waterfall method to agile.

We ask the class to split into teams, have them design some software-related thing. Simulate changing user requirements, etc. and see how teams with different styles react differently. Not sure what form this would take yet.

**Comment by EvanDorsky** [comment]
This needs more thought. There was a lot of talking in this class, though, just trying to think of a way to split it up.

**Comment by benkahle** [comment]
Addressed in suggestions
