### ISSUE TITLE
Class Folder names are not descriptive

### ISSUE THREAD

**Issue by EvanSimpson** [olinjs/olinjs#112]
`classes` subfolder list looks like
- `class01`
- `class02`
- `class03`
- `class04`

which makes it difficult to navigate from within that folder.

**Comment by EvanDorsky** [comment]
How about this @EvanSimpson?
- `class00`: `00-getting-ready`
- `class01`: `01-welcome-internet`
- `class02`: `02-javascript`
- `class03`: `03-express-templates-mongo`
- `class04`: `04-client-jquery-ajax`
- `class05`: `05-git-mini-skills`
- `class06`: `06-css-development-grace`
- `class07`: `07-apis-debugging`
- `class08`: `08-tests-tasks`
- `class09`: `09-designs-diagrams`
- `class10`: `10-clientside-frameworks`
- `class11`: `11-security`
- `class12`: `12-deployment-scaling`
- `class13`: `13-framework-presentations`
- `class14`: `14-nothing`
- `class15`: `15-agile`

**Comment by EvanSimpson** [comment]
:+1:
