### ISSUE TITLE
Add client side handlebars tutorial

### ISSUE THREAD

**Issue by benkahle** [olinjs/olinjs#85]
Courtesy of Ryan Louie:
https://github.com/youralien/twotter/blob/ryan/hw6/README.md

**Comment by ThomasTheDane** [comment]
We did have the class 10 handlebars in class. Ryan's approach is valid but not how I have traditionally seen client side handlebars function.

**Comment by benkahle** [comment]
Add this to Class 7 - Task Running

**Comment by billmwong** [comment]
I'm closing these old issues to clean up the repo.  Feel free to re-open if you feel they're still issues!
