### ISSUE TITLE
Class 1 homework needs survey link

### ISSUE THREAD

**Issue by benkahle** [olinjs/olinjs#9]
Class 1 homework should include a link to a survey (which adds its results to a new tab in the homework google doc) asking standard homework questions. See: https://docs.google.com/forms/d/1B6YfgxeIQ-QIYIsyb_1IkE7uGLvinXXH4EfO2S0cZyY/viewform

Also, the homework should assign https://github.com/sethvincent/javascripting as well.

**Comment by EvanSimpson** [comment]
Assign someone.
