### ISSUE TITLE
Provide more boilerplate/walkthrough on homeworks

### ISSUE THREAD

**Issue by benkahle** [olinjs/olinjs#96]
Cat DB: A bit abrupt from lecture to functional app. The homework should provide a walkthrough to ease into the rest of the application.

Burger App: Same as above, plus providing some boilerplate (files, maybe even suggested routes) would ease transition and point people in the right direction. Maybe walk through an Ajax communication too.

Twoter: Boilerplate?

**Comment by EvanDorsky** [comment]
There should probably be less boilerplate as the assignments go on.

**Comment by benkahle** [comment]
Addressed in future suggestions document
